spring:
  datasource:
    one:
      url: jdbc:mysql://127.0.0.1:3306/test01?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&tinyInt1isBit=false
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    two:
      url: jdbc:mysql://127.0.0.1:3306/test02?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&tinyInt1isBit=false
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

#mybatis≈‰÷√
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    call-setters-on-nulls: true